/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.anthonyescobar.system;

import javax.swing.JFrame;

/**
 *
 * @author informatica
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        backgroundLogin = new javax.swing.JPanel();
        logoGenesis = new javax.swing.JLabel();
        JpLogin = new javax.swing.JPanel();
        lbContraseña = new javax.swing.JLabel();
        txtfldUsuario = new javax.swing.JTextField();
        lbUsuario = new javax.swing.JLabel();
        jpassContraseña = new javax.swing.JPasswordField();
        lbLoginExpress = new javax.swing.JLabel();
        lbPregunta = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        lbIniciarCompras = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundLogin.setBackground(new java.awt.Color(245, 190, 0));

        logoGenesis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/anthonyescobar/images/LogoAppKinalGenesisExpress.png"))); // NOI18N

        JpLogin.setBackground(new java.awt.Color(166, 131, 12));

        lbContraseña.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        lbContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lbContraseña.setText("CONTRASEÑA");

        txtfldUsuario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtfldUsuario.setToolTipText("");

        lbUsuario.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbUsuario.setText("USUARIO");

        jpassContraseña.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        lbLoginExpress.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        lbLoginExpress.setForeground(new java.awt.Color(255, 255, 255));
        lbLoginExpress.setText("LOGIN GENESIS Express");

        lbPregunta.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lbPregunta.setForeground(new java.awt.Color(255, 255, 255));
        lbPregunta.setText("¿No tienes cuenta?  ");

        btnRegistrarse.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegistrarse.setText("REGISTRARSE");

        btnIniciarSesion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnIniciarSesion.setText("INICIO SESION");
        btnIniciarSesion.setToolTipText("");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        lbIniciarCompras.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lbIniciarCompras.setForeground(new java.awt.Color(255, 255, 255));
        lbIniciarCompras.setText("Iniciar Compras");

        javax.swing.GroupLayout JpLoginLayout = new javax.swing.GroupLayout(JpLogin);
        JpLogin.setLayout(JpLoginLayout);
        JpLoginLayout.setHorizontalGroup(
            JpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpLoginLayout.createSequentialGroup()
                .addGroup(JpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpLoginLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(JpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIniciarSesion)
                            .addComponent(lbIniciarCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrarse)))
                    .addGroup(JpLoginLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(JpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbLoginExpress, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtfldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jpassContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JpLoginLayout.setVerticalGroup(
            JpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpLoginLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbLoginExpress)
                .addGap(35, 35, 35)
                .addComponent(lbUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtfldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lbContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpassContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(JpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPregunta)
                    .addComponent(lbIniciarCompras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLoginLayout = new javax.swing.GroupLayout(backgroundLogin);
        backgroundLogin.setLayout(backgroundLoginLayout);
        backgroundLoginLayout.setHorizontalGroup(
            backgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLoginLayout.createSequentialGroup()
                .addComponent(logoGenesis)
                .addGap(7, 7, 7)
                .addComponent(JpLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        backgroundLoginLayout.setVerticalGroup(
            backgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLoginLayout.createSequentialGroup()
                .addGroup(backgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLoginLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(JpLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLoginLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(logoGenesis, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpLogin;
    private javax.swing.JPanel backgroundLogin;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPasswordField jpassContraseña;
    private javax.swing.JLabel lbContraseña;
    private javax.swing.JLabel lbIniciarCompras;
    private javax.swing.JLabel lbLoginExpress;
    private javax.swing.JLabel lbPregunta;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel logoGenesis;
    private javax.swing.JTextField txtfldUsuario;
    // End of variables declaration//GEN-END:variables
}
